//
//  PickUpModels.swift
//  Pomelo
//
//  Created by anupong dorkkunm on 26/8/2563 BE.
//  Copyright (c) 2563 anupong dorkkunm. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftyJSON
import UIKit

enum PickUpModel
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        
    }
  }
    
    enum PickupQuery
     {
       struct Request
       {
        static let query = ["filter[shop_id]":"1"]
       }
       
     }
    

    
}

