//
//  PickUpViewController.swift
//  Pomelo
//
//  Created by anupong dorkkunm on 26/8/2563 BE.
//  Copyright (c) 2563 anupong dorkkunm. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation
import PullToRefresh
import Toast_Swift

protocol PickUpDisplayLogic: class
{
  func displaySomething(viewModel: PickUpModel.Something.ViewModel)
  func displayPickupData(data:PickupData)
  func presentError(error:NSError)
   
  
}

class PickUpViewController: UIViewController, PickUpDisplayLogic
{   
  var interactor: PickUpBusinessLogic?
  var router: (NSObjectProtocol & PickUpRoutingLogic & PickUpDataPassing)?
    
    let refresher = PullToRefresh()
    var locationManager: CLLocationManager = CLLocationManager()
    @IBOutlet weak var tablePickupList: UITableView!
    
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PickUpInteractor()
    let presenter = PickUpPresenter()
    let router = PickUpRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
    self.title = "Pomelo Pick Up"
    setUpNavigateionBarButton()
  }
    
    func setUpNavigateionBarButton() {
        var image = UIImage.init(systemName: "location.fill")
        image = image?.withRenderingMode(.alwaysTemplate)
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(image: image, style:.plain, target: self, action:  #selector(callLocation))
        self.navigationItem.rightBarButtonItem?.tintColor = .black
    }
    
    override func viewDidAppear(_ animated: Bool) {
        setUptableView()
    }
    
    func setUpCorelocation()  {
        
        locationManager.desiredAccuracy = kCLLocationAccuracyBest
        locationManager.delegate = self
        locationManager.requestWhenInUseAuthorization()
        locationManager.startUpdatingLocation()
       
        if CLLocationManager.locationServicesEnabled() {
            locationManager.delegate = self
            locationManager.desiredAccuracy = kCLLocationAccuracyNearestTenMeters
            locationManager.startUpdatingLocation()
        }
        
    }
    
    func setUptableView() {
        tablePickupList.register(UINib(nibName: "PickupTableViewCell", bundle: nil), forCellReuseIdentifier: "PickupTableViewCell")
        tablePickupList.delegate = self
        tablePickupList.dataSource = self
        tablePickupList.tableFooterView = UIView(frame: .zero)
        tablePickupList.addPullToRefresh(refresher) {
            self.tablePickupList.endRefreshing(at: .top)
            self.loadPickupData()
            
            
        }
    }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    loadPickupData()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func loadPickupData()
  {
//    let request = PickUp.Something.Request()
//    interactor?.doSomething(request: request)
    interactor?.getData()
  }
  
  func displaySomething(viewModel: PickUpModel.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
  func displayPickupData(data:PickupData) {
        
        tablePickupList.reloadData()
    }
    
    func presentError(error:NSError)  {
         tablePickupList.endRefreshing(at: .top)
        self.view.makeToast(error.description)
    }
    
    @objc func callLocation(){
//        interactor.
          setUpCorelocation()
       }
}

extension PickUpViewController:UITableViewDelegate,UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return interactor?.getDataLoaded().count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let data = interactor?.getDataLoaded()[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: "PickupTableViewCell") as? PickupTableViewCell
        cell?.setData(data: data!)
        return cell!
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
    
}


extension PickUpViewController: CLLocationManagerDelegate {
    
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        manager.stopUpdatingLocation()
        interactor?.setUpdateLocation(location: locations.last!)
    }

    
}
