//
//  PickUpPresenter.swift
//  Pomelo
//
//  Created by anupong dorkkunm on 26/8/2563 BE.
//  Copyright (c) 2563 anupong dorkkunm. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PickUpPresentationLogic
{
  func presentSomething(response: PickUpModel.Something.Response)
  func presentPickupData(data:PickupData)
  func presentError(error:NSError)
}

class PickUpPresenter: PickUpPresentationLogic
{
  weak var viewController: PickUpDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PickUpModel.Something.Response)
  {
    let viewModel = PickUpModel.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func presentPickupData(data:PickupData)  {
        viewController?.displayPickupData(data: data)
    }
    
    func presentError(error:NSError) {
        viewController?.presentError(error: error)
    }
    
}
